# Use root/example as user/password credentials
version: '3.1'

services:
  mongoBlogapp:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongo123
