# Use root/example as user/password credentials
version: '3.1'

services:
  mongoBlogapp:
    image: mongo:4.4.6
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
