# Use root/example as user/password credentials
version: '3.1'

networks:
  blogapp_default:
    driver: bridge 

services:
  mongoBlogapp:
    image: mongo:4.4.6
    ports:
      - ${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - blogapp_default
     
  web:
    build: .
    command: npm run start
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - /home/blogApp
    depends_on:
      - mongoBlogapp
    links:
      - mongoBlogapp
    networks:
      - blogapp_default
