version: '3.8'

networks:
  blogapp_default:
    driver: bridge

services:
  mongoBlogapp:
    image: mongo:4.4.6
    container_name: mongoBlogapp
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - blogapp_default

  web:
    build: .
    container_name: blogApp
    command: npm start
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/home/blogApp
    depends_on:
      - mongoBlogapp
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DOCKER_PORT=mongoBlogapp
      - MONGO_PORT=${MONGO_PORT}
      - WEB_PORT=${WEB_PORT}
    networks:
      - blogapp_default
